baseURL               = "https://80d4cbbd.webstack-hugo-181818818.pages.dev/"
languageCode          = "zh-CN"
title                 = "我的网址导航"
preserveTaxonomyNames = true
disablePathToLower    = true
hasCJKLanguage        = true
publishDir            = "public"

[params]
    author        = "shenweiyan"
    description   = "Webstack-Hugo 网址导航 | 我的个性化导航站"
    upload        = ""
    about         = ""
    repository    = ""
    enablePreLoad = true
    textPreLoad   = "正在加载导航..."
    expandSidebar = false
    logosPath     = "assets/images/logos"
    defaultLogo   = "assets/images/logos/default.webp"
    nightMode     = false
    yiyan         = true
    fancybox      = true

[params.seo]    
    baiduhmid       = ''
    baiduSiteVer    = ''

[params.qweather]
    key = "085791e805a24491b43b06cf58ab31e7"

[params.images]
    favicon           = "assets/images/bi-favicon.png"
    searchImageL      = "assets/images/bg-dna.jpg"
    searchImageD      = "assets/images/bg-dna.jpg"
    logoExpandLight   = "assets/images/bi-expand-dark.png"
    logoExpandDark    = "assets/images/bi-expand-light.png"
    logoCollapseLight = "assets/images/bi.png"
    logoCollapseDark  = "assets/images/bi.png"
    
[markup.goldmark.renderer]
    unsafe = true

[params.footer]
    copyright = '&copy; 2024 By 我的导航站 | Powered by WebStack-Hugo'
